### ISSUE TITLE
Unsearchable Hidden Abilities

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#192]
Look into why some Pokemon do not show up when searching for certain abilities using ability filters:
Examples:
- Skill Link missing Aipom
- Sniper missing Ariados

They're still listed if the filter is a custom filter and I've only found examples for hidden abilities

**Comment by theastrogoth** [comment]
I'm unable to replicate this (what browser, by the way?), but it sounds like it might be a problem with the `GroupedVirtuoso`. 

I had noticed something similar happening with Friend Guard, but it turned out that for some reason certain filters caused the list to skip rendering the 0th index of the results data (which is consistent with Aipom and Ariados being the missing results). Resorting reverse-alphabetically would show the missing result at the bottom of the list and trim a different specie off the top. Strangely, the full list would be shown when starting to type another input and then backspacing.

I thought I had fixed it by filtering out empty groups in the `GroupedVirtuoso`, but maybe there is still a lingering problem there.

**Comment by Ericzklm** [comment]
Huh, I'm also no longer able to reproduce it (Chrome). Aipom and Ariados are just the first couple of examples I could find scrolling down, it could have applied to other Pokemon lower down in the alphabet but I didn't check that. The issue did not happen with Alomomola, Annihilape, & Appletun who would also be index 0 when searching their abilities. Pretty baffling all-in-all.
