### ISSUE TITLE
Save Info Functionality

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#27]
Add the ability to import and export the full page including all 5 builds and the moves, probably as a json or other data format.

If it's reasonable, a way to access a build through a hash in the URL would be nice, but I imagine this would probably require a database to store these data objects and that may have actual cost. Maybe a few official setups can be accessed without a database so maybe adding something like ...#rillaboom to the url will give you the official setup.

**Comment by theastrogoth** [comment]
I've had some luck with storing compressed info in the URL hash in other cases. Sharing would require sharing of a link instead of builds being available for everyone from a database, but I think this is pretty reasonable for now. I can always add builds to directly to the repo. 

I like the "#rillaboom" idea a lot!
