### ISSUE TITLE
Flame Orb Speed Dependency

### ISSUE THREAD

**Issue by Ericzklm** [theastrogoth/tera-raid-builder#58]
https://github.com/theastrogoth/tera-raid-builder/blob/4da94d38cb3b62c8a4244e162d38f3a42bfeb90d/src/raidcalc/RaidMove.ts#L128

Flame Orb does not activate if you move before the raid boss. Would passing in `true` break any of the mechanics (do any items effects not work at the end of the turn)?

**Comment by theastrogoth** [comment]
Good catch!

The idea was for Flame Orb to take effect at the end of a turn rather than at the end of a move. If the Raider moves before the raid boss, the burn should take effect after the Raid Boss' move rather than in between their moves. Just passing true would cause the burn to happen early, which would change the damage of moves like Hex.

It seems I didn't add any way for that to actually happen when the Raider moves first, since currently, only the move user is checked for orb possession.

Maybe those item effects should be moved from RaidMove to RaidTurn
